name: PR Checks

on:
  pull_request:
    branches: [ main, develop ]
  pull_request_target:
    branches: [ main, develop ]

jobs:
  quick-checks:
    name: Quick Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: package-lock.json
        
    - name: Configure npm
      run: |
        npm config set registry https://registry.npmjs.org/
        npm config delete //registry.npmjs.org/:_authToken || true
        npm cache clean --force
        
    - name: Install backend dependencies
      run: npm install --no-audit
      
    - name: Install frontend dependencies
      working-directory: frontend
      run: npm install --no-audit
      
    - name: Create uploads directory
      run: mkdir -p uploads
      
    - name: Run backend tests
      run: npm test
      env:
        NODE_ENV: test
        DATABASE_URL: file:./test.db
        
    - name: Run frontend tests
      working-directory: frontend
      run: npm test -- --watchAll=false --passWithNoTests
      env:
        CI: true
        REACT_APP_API_BASE_URL: http://localhost:3000/api
        REACT_APP_BACKEND_URL: http://localhost:3000
        
    - name: TypeScript check
      working-directory: frontend
      run: npx tsc --noEmit
      
    - name: Build frontend
      working-directory: frontend
      run: npm run build
      env:
        REACT_APP_API_BASE_URL: https://api.example.com/api
        REACT_APP_BACKEND_URL: https://api.example.com

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: package-lock.json
        
    - name: Configure npm
      run: |
        npm config set registry https://registry.npmjs.org/
        npm config delete //registry.npmjs.org/:_authToken || true
        npm cache clean --force
        
    - name: Install backend dependencies
      run: npm install --no-audit
      
    - name: Install frontend dependencies
      working-directory: frontend
      run: npm install --no-audit
      
    - name: Run npm audit (backend)
      run: npm audit --audit-level=high
      
    - name: Run npm audit (frontend)
      working-directory: frontend
      run: npm audit --audit-level=high
