name: PR Checks

on:
  pull_request:
    branches: [ main, develop ]
  pull_request_target:
    branches: [ main, develop ]

jobs:
  quick-checks:
    name: Quick Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: Verify package-lock.json exists
      run: |
        echo "Checking package-lock.json files..."
        ls -la package-lock.json
        ls -la frontend/package-lock.json
        echo "✅ Package lock files found"
        
    - name: Create uploads directory
      run: mkdir -p uploads
      
    - name: Verify file structure
      run: |
        echo "Verifying project structure..."
        ls -la
        ls -la frontend/src/
        echo "✅ Project structure verified"
        
    - name: Check for critical files
      run: |
        echo "Checking for critical project files..."
        test -f package.json && echo "✅ package.json found"
        test -f frontend/package.json && echo "✅ frontend/package.json found"
        test -f src/server.js && echo "✅ server.js found"
        test -f frontend/src/App.tsx && echo "✅ App.tsx found"
        echo "✅ All critical files present"

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: Verify dependencies
      run: |
        echo "Checking package.json files..."
        cat package.json | jq '.dependencies | keys'
        cat frontend/package.json | jq '.dependencies | keys'
        echo "✅ Dependencies verified"
        
    - name: Check for security issues in code
      run: |
        echo "Checking for common security issues..."
        # Check for hardcoded secrets
        if grep -r "password\|secret\|key\|token" src/ --include="*.js" --include="*.ts" --include="*.tsx" | grep -v "//\|#" | grep -v "process.env"; then
          echo "⚠️  Potential hardcoded secrets found"
        else
          echo "✅ No obvious hardcoded secrets found"
        fi
        echo "✅ Security check completed"
