name: PR Checks

on:
  pull_request:
    branches: [ main, develop ]
  pull_request_target:
    branches: [ main, develop ]

jobs:
  quick-checks:
    name: Quick Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: Verify package-lock.json exists
      run: |
        echo "Checking package-lock.json files..."
        ls -la package-lock.json
        ls -la frontend/package-lock.json
        echo "✅ Package lock files found"
        
    - name: Create uploads directory
      run: mkdir -p uploads
      
    - name: TypeScript check (frontend)
      working-directory: frontend
      run: |
        echo "Checking TypeScript compilation..."
        npx tsc --noEmit --skipLibCheck
        echo "✅ TypeScript check passed"
      
    - name: Verify file structure
      run: |
        echo "Verifying project structure..."
        ls -la
        ls -la frontend/src/
        echo "✅ Project structure verified"

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: Verify dependencies
      run: |
        echo "Checking package.json files..."
        cat package.json | jq '.dependencies | keys'
        cat frontend/package.json | jq '.dependencies | keys'
        echo "✅ Dependencies verified"
